#pragma once
#include <algorithm>
#include <charconv>
#include <cstdint>
#include <functional>
#include <tuple>
#include <cstdio>
#include <cmath>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>
